specVersion: 0.2.0
name: nodle-transactions-historyV1.0.0
version: 1.0.0
#runner:
#  node:
#    name: '@subql/node'
#    version: 1.2.1
#  query:
#    name: '@subql/query'
#    version: 1.0.0
description: Nova SubQuery project
repository: https://github.com/nova-wallet/subquery-nova
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x97da7ede98d7bad4e36b4d734b6055425a3be036da2a332ea5a7037656427a21'
  #chainId: '0x97da7ede98d7bad4e36b4d734b6055425a3be036da2a332ea5a7037656427a21'
  endpoint: 'wss://nodle-parachain.api.onfinality.io/ws?apikey=07f15f84-2391-4ac6-9397-d840c0141bb0'
  dictionary: 'https://api.subquery.network/sq/subquery/nodle-dictionary'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 432000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleHistoryElement
          kind: substrate/CallHandler
        - handler: handleReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleRewarded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
        - handler: handleSlashed
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slashed
        - handler: handleBonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleUnbonded
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Unbonded
        - handler: handleTransfer
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleTransferKeepAlive
          kind: substrate/EventHandler
          filter:
            module: balances
            method: transfer_keep_alive
        - handler: handleNewEra
          kind: substrate/EventHandler
          filter:
            module: staking
            method: StakingElection
        - handler: handleStakersElected
          kind: substrate/EventHandler
          filter:
            module: staking
            method: StakersElected
